name: simpsons-classification
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.5.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - jupyter>=1.0.0
  - notebook>=6.5.0
  - ipykernel>=6.15.0
  - tqdm>=4.64.0
  - pillow>=9.0.0
  - pip
  - pip:
    - opencv-python>=4.8.0
    - scikit-image>=0.19.0
